# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.srcs/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/axi_pwm_test_axi_smc_0.xci
# IP: The module: 'axi_pwm_test_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/bd_0e5f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_1/bd_0e5f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_2/bd_0e5f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_3/bd_0e5f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_4/bd_0e5f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_5/bd_0e5f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_6/bd_0e5f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_7/bd_0e5f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_8/bd_0e5f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_9/bd_0e5f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_10/bd_0e5f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_11/bd_0e5f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_12/bd_0e5f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_1/bd_0e5f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_5/bd_0e5f_s00a2s_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_6/bd_0e5f_sarn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_7/bd_0e5f_srn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_8/bd_0e5f_sawn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_9/bd_0e5f_swn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_10/bd_0e5f_sbn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_11/bd_0e5f_m00s2a_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.srcs/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/axi_pwm_test_axi_smc_0.xci
# IP: The module: 'axi_pwm_test_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/bd_0e5f.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_1/bd_0e5f_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_2/bd_0e5f_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_3/bd_0e5f_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_4/bd_0e5f_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_5/bd_0e5f_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_6/bd_0e5f_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_7/bd_0e5f_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_8/bd_0e5f_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_9/bd_0e5f_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_10/bd_0e5f_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_11/bd_0e5f_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_12/bd_0e5f_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_1/bd_0e5f_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_5/bd_0e5f_s00a2s_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_6/bd_0e5f_sarn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_7/bd_0e5f_srn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_8/bd_0e5f_sawn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_9/bd_0e5f_swn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_10/bd_0e5f_sbn_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/bd_0/ip/ip_11/bd_0e5f_m00s2a_0_ooc.xdc

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
