# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/axi_pwm_test/axi_pwm_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test || ORIG_REF_NAME==axi_pwm_test} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_microblaze_0_0/axi_pwm_test_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_microblaze_0_0 || ORIG_REF_NAME==axi_pwm_test_microblaze_0_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_dlmb_v10_0/axi_pwm_test_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_dlmb_v10_0 || ORIG_REF_NAME==axi_pwm_test_dlmb_v10_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_ilmb_v10_0/axi_pwm_test_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_ilmb_v10_0 || ORIG_REF_NAME==axi_pwm_test_ilmb_v10_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_dlmb_bram_if_cntlr_0/axi_pwm_test_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_pwm_test_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_ilmb_bram_if_cntlr_0/axi_pwm_test_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==axi_pwm_test_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_lmb_bram_0/axi_pwm_test_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_lmb_bram_0 || ORIG_REF_NAME==axi_pwm_test_lmb_bram_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_mdm_1_0 || ORIG_REF_NAME==axi_pwm_test_mdm_1_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_clk_wiz_1_0/axi_pwm_test_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_clk_wiz_1_0 || ORIG_REF_NAME==axi_pwm_test_clk_wiz_1_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_rst_clk_wiz_1_100M_0/axi_pwm_test_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==axi_pwm_test_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_Axi_Pwm_IP_0_0/axi_pwm_test_Axi_Pwm_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_Axi_Pwm_IP_0_0 || ORIG_REF_NAME==axi_pwm_test_Axi_Pwm_IP_0_0} -quiet] -quiet

# IP: bd/axi_pwm_test/ip/axi_pwm_test_axi_smc_0/axi_pwm_test_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_pwm_test_axi_smc_0 || ORIG_REF_NAME==axi_pwm_test_axi_smc_0} -quiet] -quiet

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/axi_pwm_test_ooc.xdc
