# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.srcs/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0.xci
# IP: The module: 'axi_pwm_test_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.srcs/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0.xci
# IP: The module: 'axi_pwm_test_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lonewolf/Vivado/beginner_projects/Axi_Pwm_Test/Axi_Pwm_Test.gen/sources_1/bd/axi_pwm_test/ip/axi_pwm_test_mdm_1_0/axi_pwm_test_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_pwm_test_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
